package viewFomularios;

import java.awt.Font;
import java.util.Date;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import controller.SalaController;
import model.Cliente;
import model.Filme;
import servico.ClienteServico;
import servico.FilmeServico;
import servico.SalaServico;
import util.DateUtil;

/**
 *
 * @author Thiago
 */
public class FormularioSala extends javax.swing.JPanel {

    private SalaServico servicoSala;
    private FilmeServico servicoV;
    private SalaController controller;

    /**
     * Creates new form FormularioSala
     */
    public FormularioSala(SalaController control) {
    	servicoSala = new SalaServico();
    	servicoV = new FilmeServico();
        controller = control;
        initComponents();
    }

    public FormularioSala() {
    	servicoSala = new SalaServico();
    	servicoV = new FilmeServico();
        controller = new SalaController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMensagem = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabelFilme = new javax.swing.JLabel();
        jLabelPoltronas = new javax.swing.JLabel();
        jComboBoxSala = new javax.swing.JComboBox();
        txtPoltronas = new javax.swing.JTextField();
        jBCadastrar = new javax.swing.JButton();
        jBVoltar = new javax.swing.JButton();
        jLabelID = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(127, 0));

        jLabelMensagem.setFont(new Font("Tahoma", Font.BOLD, 25)); // NOI18N
        jLabelMensagem.setText("Cadastro de Salas");

        jLabelNumero.setFont(new Font("Tahoma", Font.PLAIN, 15)); // NOI18N
        jLabelNumero.setText("Numero:");

        jLabelFilme.setFont(new Font("Tahoma", Font.PLAIN, 15)); // NOI18N
        jLabelFilme.setText("Filme:");

        jLabelPoltronas.setFont(new Font("Tahoma", Font.PLAIN, 15)); // NOI18N
        jLabelPoltronas.setText("Poltronas:");

        jComboBoxSala.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jComboBoxSala.setModel(new comboBoxModel.VooComboBoxModel());
        jComboBoxSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSalaActionPerformed(evt);
            }
        });

        jBCadastrar.setFont(new Font("Tahoma", Font.PLAIN, 15)); // NOI18N
        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        jBVoltar.setFont(new Font("Tahoma", Font.PLAIN, 15)); // NOI18N
        jBVoltar.setText("Voltar");
        jBVoltar.setMaximumSize(new java.awt.Dimension(131, 25));
        jBVoltar.setMinimumSize(new java.awt.Dimension(131, 25));
        jBVoltar.setPreferredSize(new java.awt.Dimension(131, 25));
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jLabelID.setFont(new Font("Tahoma", Font.PLAIN, 15)); // NOI18N
        jLabelID.setText("ID:");

        txtId.setEditable(false);
        GroupLayout groupLayout = new GroupLayout(this);
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(109)
        			.addComponent(jLabelID)
        			.addGap(45)
        			.addComponent(txtId, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(91)
        			.addComponent(jLabelNumero)
        			.addGap(27)
        			.addComponent(txtNumero, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(87)
        			.addComponent(jLabelPoltronas)
        			.addGap(24)
        			.addComponent(txtPoltronas, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(100)
        			.addComponent(jLabelFilme)
        			.addGap(37)
        			.addComponent(jComboBoxSala, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(539)
        			.addComponent(jLabel2))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(82)
        			.addComponent(jBCadastrar, GroupLayout.PREFERRED_SIZE, 134, GroupLayout.PREFERRED_SIZE)
        			.addGap(46)
        			.addComponent(jBVoltar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(134)
        			.addComponent(jLabelMensagem))
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabelMensagem, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
        			.addGap(59)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabelID)
        				.addComponent(txtId, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(7)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabelNumero)
        				.addComponent(txtNumero, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(7)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabelPoltronas)
        				.addComponent(txtPoltronas, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(6)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(3)
        					.addComponent(jLabelFilme))
        				.addComponent(jComboBoxSala, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(90)
        			.addComponent(jLabel2)
        			.addGap(15)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jBCadastrar)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(1)
        					.addComponent(jBVoltar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        );
        setLayout(groupLayout);
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        if (getjBCadastrar().getText().equalsIgnoreCase("Editar")) {
            editarSala();
            controller.voltarPrincipal();
        } else {
            cadastrarSala();            
        }
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jComboBoxSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVooActionPerformed
        if(jComboBoxSala.getSelectedIndex() > - 1){
            carregaText();                    
        }
    }//GEN-LAST:event_jComboBoxVooActionPerformed

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        controller.voltarPrincipal();
    }//GEN-LAST:event_jBVoltarActionPerformed
    private void editarSala() {
        int idSala = Integer.parseInt(txtId.getText());         
        if (servicoSala.salaExiste(idSala)) {
            Cliente comprador = servicoCliente.devolveCliente(idSala);
//            System.out.println("Cliente selecionado com sucesso...");
            Voo vooSelect = (Voo) jComboBoxSala.getSelectedItem();
            int idVoo = vooSelect.getCodigo();
            if (servicoV.vooExiste(idVoo)) {
                Voo vooSel = servicoV.entregaVoo(idVoo);
                Date atual = new Date();
                int idSala = Integer.parseInt(txtId.getText());
                servicoP.atualizaSala(new Sala(idSala, comprador, vooSel, atual));
                JOptionPane.showMessageDialog(this, "Venda atualizada com sucesso...");
            } else {
                JOptionPane.showMessageDialog(this, "Voo não encontrado!!!", "Erro: Ao selecionar o Voo", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Cliente não encontrado!!!", "Erro: Ao selecionar o Cliente", JOptionPane.ERROR_MESSAGE);            
    }

    private void cadastrarSala() {
        String rgComprador = txtNumero.getText();
        Cliente comprador = null;
        if (servicoCliente.clienteExiste(rgComprador)) {
            comprador = servicoCliente.devolveCliente(rgComprador);
//            System.out.println("Cliente selecionado com sucesso...");
            Voo vooSel = (Voo) jComboBoxSala.getSelectedItem();
            int idVoo = vooSel.getCodigo();
            if (servicoV.vooExiste(idVoo)) {
                vooSel = servicoV.entregaVoo(idVoo);
                Date atual = new Date();
                servicoP.addSala(new Sala(comprador, vooSel, atual));
                JOptionPane.showMessageDialog(this, "Venda cadastrada com sucesso...");
            } else {
                JOptionPane.showMessageDialog(this, "Voo não encontrado!!!", "Erro: Ao selecionar o Voo", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Cliente não encontrado!!!", "Erro: Ao selecionar o Cliente", JOptionPane.ERROR_MESSAGE);            
    }

    public JButton getjBCadastrar() {
        return jBCadastrar;
    }

    public JButton getjBVoltar() {
        return jBVoltar;
    }

    public JComboBox getjComboBoxVoo() {
        return jComboBoxSala;
    }

    public JLabel getjLabelMensagem() {
        return jLabelMensagem;
    }

    public void habilitaEdicaoFormSala(boolean valor) {
        this.txtNumero.setEditable(valor);
    }
    
    public void limparCampos() {
        txtId.setText("");
        jComboBoxSala.setSelectedIndex(-1);
        txtNumero.setText("");
        txtPoltronas.setText(" ");
    }

    public JLabel getjLabelID() {
        return jLabelID;
    }

    public JTextField getjTextFieldID() {
        return txtId;
    }
    
    public void carregaText() {
        Filme filme = (Filme)jComboBoxSala.getSelectedItem();
        jTextDestino.setText(filme.getDestino().getNome());
        txtPoltronas.setText(filme.getOrigem().getNome());
    }
    
    public void carregaDados(int id, String rg, Voo voo, Date horaAtual) {
        this.txtId.setText(Integer.toString(id));
        this.txtNumero.setText(rg);  
        this.jComboBoxSala.getModel().setSelectedItem(voo);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JComboBox jComboBoxSala;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFilme;
    private javax.swing.JLabel jLabelPoltronas;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelMensagem;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPoltronas;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables

}