package viewFomularios;

import controller.PassagemController;
import model.Voo;
import servico.VooServico;
import java.text.ParseException;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import util.DateUtil;
import servico.ClienteServico;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import model.Cliente;
import model.Passagem;
import servico.PassagemServico;

/**
 *
 * @author Thiago
 */
public class FormularioPassagem extends javax.swing.JPanel {

    private ClienteServico servicoC;
    private VooServico servicoV;
    private PassagemServico servicoP;
    private PassagemController controller;

    /**
     * Creates new form FormularioPassagem
     */
    public FormularioPassagem(PassagemController control) {
        servicoP = new PassagemServico();
        servicoC = new ClienteServico();
        servicoV = new VooServico();
        controller = control;
        initComponents();
    }

    public FormularioPassagem() {
        servicoV = new VooServico();
        controller = new PassagemController();
        servicoC = new ClienteServico();
        servicoP = new PassagemServico();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMensagem = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelRG = new javax.swing.JLabel();
        jTextRG = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxVoo = new javax.swing.JComboBox();
        jTextOrigem = new javax.swing.JTextField();
        jTextDestino = new javax.swing.JTextField();
        jTextDataHora = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jBCadastrar = new javax.swing.JButton();
        jBVoltar = new javax.swing.JButton();
        jLabelHoraAtual = new javax.swing.JLabel();
        jTextHoraAtual = new javax.swing.JTextField();
        jLabelID = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabelObservacao = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(127, 0));

        jLabelMensagem.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
        jLabelMensagem.setText("Preencha com os Dados da Passagem");

        jLabelRG.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabelRG.setText("RG:");

        jLabel4.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel4.setText("Voo:");

        jLabel5.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel5.setText("Origem:");

        jComboBoxVoo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jComboBoxVoo.setModel(new comboBoxModel.VooComboBoxModel());
        jComboBoxVoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVooActionPerformed(evt);
            }
        });

        jTextOrigem.setEditable(false);

        jTextDestino.setEditable(false);

        jTextDataHora.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel6.setText("Destino:");

        jLabel7.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel7.setText("Partida do Voo:");

        jBCadastrar.setFont(new java.awt.Font("Lucida Console", 1, 16)); // NOI18N
        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        jBVoltar.setFont(new java.awt.Font("Lucida Console", 1, 16)); // NOI18N
        jBVoltar.setText("Voltar");
        jBVoltar.setMaximumSize(new java.awt.Dimension(131, 25));
        jBVoltar.setMinimumSize(new java.awt.Dimension(131, 25));
        jBVoltar.setPreferredSize(new java.awt.Dimension(131, 25));
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jLabelHoraAtual.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabelHoraAtual.setText("Horário da Compra");

        jTextHoraAtual.setEditable(false);

        jLabelID.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabelID.setText("ID:");

        jTextFieldID.setEditable(false);

        jLabelObservacao.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabelObservacao.setText("Obs:Hora gerada do sistema");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelRG)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabelID)))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelHoraAtual, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextRG)
                                    .addComponent(jTextOrigem)
                                    .addComponent(jTextDataHora)
                                    .addComponent(jTextHoraAtual))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelObservacao))
                            .addComponent(jComboBoxVoo, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jBCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabelMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelID)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRG)
                    .addComponent(jTextRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxVoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHoraAtual)
                    .addComponent(jTextHoraAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelObservacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        if (getjBCadastrar().getText().equalsIgnoreCase("Editar")) {
            editarPassagem();
            controller.voltarPrincipal();
        } else {
            cadastrarPassagem();            
        }
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jComboBoxVooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVooActionPerformed
        if(jComboBoxVoo.getSelectedIndex() > - 1){
            carregaText();                    
        }
    }//GEN-LAST:event_jComboBoxVooActionPerformed

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        controller.voltarPrincipal();
    }//GEN-LAST:event_jBVoltarActionPerformed
    private void editarPassagem() {
        String rgComprador = jTextRG.getText();         
        if (servicoC.clienteExiste(rgComprador)) {
            Cliente comprador = servicoC.devolveCliente(rgComprador);
//            System.out.println("Cliente selecionado com sucesso...");
            Voo vooSelect = (Voo) jComboBoxVoo.getSelectedItem();
            int idVoo = vooSelect.getCodigo();
            if (servicoV.vooExiste(idVoo)) {
                Voo vooSel = servicoV.entregaVoo(idVoo);
                Date atual = new Date();
                int idPassagem = Integer.parseInt(jTextFieldID.getText());
                servicoP.atualizaPassagem(new Passagem(idPassagem, comprador, vooSel, atual));
                JOptionPane.showMessageDialog(this, "Venda atualizada com sucesso...");
            } else {
                JOptionPane.showMessageDialog(this, "Voo não encontrado!!!", "Erro: Ao selecionar o Voo", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Cliente não encontrado!!!", "Erro: Ao selecionar o Cliente", JOptionPane.ERROR_MESSAGE);            
    }

    private void cadastrarPassagem() {
        String rgComprador = jTextRG.getText();
        Cliente comprador = null;
        if (servicoC.clienteExiste(rgComprador)) {
            comprador = servicoC.devolveCliente(rgComprador);
//            System.out.println("Cliente selecionado com sucesso...");
            Voo vooSel = (Voo) jComboBoxVoo.getSelectedItem();
            int idVoo = vooSel.getCodigo();
            if (servicoV.vooExiste(idVoo)) {
                vooSel = servicoV.entregaVoo(idVoo);
                Date atual = new Date();
                servicoP.addPassagem(new Passagem(comprador, vooSel, atual));
                JOptionPane.showMessageDialog(this, "Venda cadastrada com sucesso...");
            } else {
                JOptionPane.showMessageDialog(this, "Voo não encontrado!!!", "Erro: Ao selecionar o Voo", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Cliente não encontrado!!!", "Erro: Ao selecionar o Cliente", JOptionPane.ERROR_MESSAGE);            
    }

    public JButton getjBCadastrar() {
        return jBCadastrar;
    }

    public JButton getjBVoltar() {
        return jBVoltar;
    }

    public JComboBox getjComboBoxVoo() {
        return jComboBoxVoo;
    }

    public JLabel getjLabelHoraComprada() {
        return jLabelHoraAtual;
    }

    public JLabel getjLabelMensagem() {
        return jLabelMensagem;
    }

    public JTextField getjTextHoraCompra() {
        return jTextHoraAtual;
    }

    public void habilitaEdicaoFormPassagem(boolean valor) {
        this.jTextRG.setEditable(valor);
        //depois conferir como estou fazendo as anulações do ComboBox
        this.jTextHoraAtual.setEditable(false);
    }
    
    public void limparCampos() {
        jTextFieldID.setText("");
        jComboBoxVoo.setSelectedIndex(-1);
        jTextRG.setText("");
        jTextDataHora.setText("");
        jTextDestino.setText(" ");
        jTextOrigem.setText(" ");
        jTextHoraAtual.setText(" ");
    }

    public JLabel getjLabelID() {
        return jLabelID;
    }

    public JTextField getjTextFieldID() {
        return jTextFieldID;
    }
    
    public void carregaText() {
        Voo voo = (Voo)jComboBoxVoo.getSelectedItem();
        String h = DateUtil.dateHourToString(voo.getHorarioDoVoo());
        jTextDestino.setText(voo.getDestino().getNome());
        jTextOrigem.setText(voo.getOrigem().getNome());
        jTextDataHora.setText(h);        
    }
    
    public void carregaDados(int id, String rg, Voo voo, Date horaAtual) {
        this.jTextFieldID.setText(Integer.toString(id));
        this.jTextRG.setText(rg);  
        this.jComboBoxVoo.getModel().setSelectedItem(voo);
        this.jTextHoraAtual.setText(DateUtil.dateHourToString(horaAtual));        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JComboBox jComboBoxVoo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelHoraAtual;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelMensagem;
    private javax.swing.JLabel jLabelObservacao;
    private javax.swing.JLabel jLabelRG;
    private javax.swing.JTextField jTextDataHora;
    private javax.swing.JTextField jTextDestino;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextHoraAtual;
    private javax.swing.JTextField jTextOrigem;
    private javax.swing.JTextField jTextRG;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getjLabelHoraAtual() {
        return jLabelHoraAtual;
    }

    public javax.swing.JTextField getjTextHoraAtual() {
        return jTextHoraAtual;
    }

    public JLabel getjLabelObservacao() {
        return jLabelObservacao;
    }
}
