package viewFomularios;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import model.Cliente;
import servico.ClienteServico;
import controller.ClienteController;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Thiago
 */
public class FormularioCliente extends javax.swing.JPanel {
    ClienteServico servicoC;
    ClienteController controller;

    /**
     * Creates new form PainelFormularioCliente
     */
    public FormularioCliente(ClienteController control) {
        servicoC = new ClienteServico();
        controller = control;
        initComponents();
    }
    
    public FormularioCliente() {
        servicoC = new ClienteServico();
        controller = new ClienteController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jbCadastrar = new javax.swing.JButton();
        jLabelMensagem = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jbVoltar = new javax.swing.JButton();
        jtRG = new javax.swing.JTextField();
        jftTelefone = new javax.swing.JFormattedTextField();
        jLabelID = new javax.swing.JLabel();
        jtID = new javax.swing.JTextField();
        jLabelObservacao = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(620, 407));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel4.setText("OBS:4 dígitos antes do hífen e 4 depois ");

        jbCadastrar.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        jbCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCadastrarKeyPressed(evt);
            }
        });

        jLabelMensagem.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
        jLabelMensagem.setText("Preencha os dados do Cliente");

        jLabel1.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel2.setText("RG:");

        jLabel3.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel3.setText("Telefone:");

        jtNome.setPreferredSize(null);
        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNomeKeyPressed(evt);
            }
        });

        jbVoltar.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jbVoltar.setText("Voltar");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });

        jtRG.setPreferredSize(null);
        jtRG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtRGKeyPressed(evt);
            }
        });

        try {
            jftTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftTelefone.setPreferredSize(null);
        jftTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftTelefoneActionPerformed(evt);
            }
        });
        jftTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jftTelefoneKeyPressed(evt);
            }
        });

        jLabelID.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabelID.setText("ID:");

        jLabelObservacao.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabelObservacao.setText("Obs: O Campo ID não pode ser alterado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(jbVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(145, 145, 145)))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelID)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtRG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jftTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jtID)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabelObservacao)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelObservacao)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelID)
                    .addComponent(jtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jftTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        if(jbCadastrar.getText().equalsIgnoreCase("Editar")){
            editarCliente();
            controller.voltarPrincipal();
        }
        else{
            cadastrarCliente();
            controller.voltarPrincipal();
        }
    }//GEN-LAST:event_jbCadastrarActionPerformed
    
    public void cadastrarCliente() {
        String rg = jtRG.getText();
        if (servicoC.clienteExiste(rg)) {
            JOptionPane.showMessageDialog(this, " RG já existente no banco", "Erro: Cliente Existente", JOptionPane.ERROR_MESSAGE);
        } else if (rg.replace(" ", "").isEmpty() /*testando se é vazio*/) {
            JOptionPane.showMessageDialog(this, " Erro: RG VAZIO", "Erro: RG em branco", JOptionPane.ERROR_MESSAGE);
        } else if (rg.matches("\\d{10,10}")) {
            String nome = jtNome.getText();
            if (nome.matches("\\s*")) {//testar com \s para ver se é vazio
                JOptionPane.showMessageDialog(this, " Erro: NOME VAZIO", "Erro: NOME em branco", JOptionPane.ERROR_MESSAGE);
            } else if (nome.matches("[A-Za-z]+(\\s[A-Za-z]+)*")) {
                String telefone = jftTelefone.getText();
                if (!telefone.matches("\\d{4,4}-\\d{4,4}")) {
                    JOptionPane.showMessageDialog(this, " Erro: Telefone digitado diferente do formato indicado!!!", "Erro: Formato Inválido", JOptionPane.ERROR_MESSAGE);
                } else {
                    servicoC.addCliente(new Cliente(nome, rg, telefone));
                    JOptionPane.showMessageDialog(this, " Cliente " + nome + " \ncadastrado com sucesso!\n");
                }
            } else {
                JOptionPane.showMessageDialog(this, " Erro: O nome não pode conter números, caracteres especiais, ou começa em espaço ou ter mais de um espaço", "Formato Inválido", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, " Erro:O RG não pode conter letras, espaços e no máximo 10 dígitos", "Formato Inválido", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void editarCliente() {
        //servicoC.mostrarClientes();
        int idClienteUpdate = (Integer.parseInt(jtID.getText()));
        if (servicoC.clienteExiste(idClienteUpdate)) {
            String rg = jtRG.getText();
            if (rg.replace(" ", "").isEmpty() /*testando se é vazio*/) {
                JOptionPane.showMessageDialog(this, " Erro: RG VAZIO", "Erro: RG em branco", JOptionPane.ERROR_MESSAGE);
            } else if (rg.matches("\\d{10,10}")) {
                String nome = jtNome.getText();
                if (nome.matches("\\s*")) {//testar com \s para ver se é vazio
                    JOptionPane.showMessageDialog(this, " Erro: NOME VAZIO", "Erro: NOME em branco", JOptionPane.ERROR_MESSAGE);
                } else if (nome.matches("[A-Za-z]+(\\s[A-Za-z]+)*")) {
                    String telefone = jftTelefone.getText();
                    if (!telefone.matches("\\d{4,4}-\\d{4,4}")) {
                        JOptionPane.showMessageDialog(this, " Erro: Telefone digitado diferente do formato indicado!!!", "Formato Inválido", JOptionPane.ERROR_MESSAGE);
                    } else {
                        servicoC.atualizaCliente(new Cliente(idClienteUpdate, nome, rg, telefone));
                        JOptionPane.showMessageDialog(this, " Cliente " + nome + " atualizado com sucesso!\n");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, " Erro: O nome não pode conter números, caracteres especiais, ou começa em espaço ou ter mais de um espaço", "Formato Inválido", JOptionPane.ERROR_MESSAGE );
                }
            } else {
                JOptionPane.showMessageDialog(this, "\nErro:O RG não pode conter letras, espaços e no máximo 10 dígitos", "Formato Inválido", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    public void carregaDados(int id, String nome, String RG, String tel){   
        this.jtID.setText(Integer.toString(id));
        this.jtNome.setText(nome);
        this.jtRG.setText(RG);
        this.jftTelefone.setText(tel);
    }
    
    public void limparCampos() {
        jtRG.setText("");
        jtNome.setText("");
        jftTelefone.setText("");
    }
    
    public javax.swing.JButton getJbCadastrar() {
        return jbCadastrar;
    }
    
    public void habilitaEdicaoFormCliente(boolean valor) {
        this.jtID.setEditable(false);
        this.jtRG.setEditable(valor);
        this.jtNome.setEditable(valor);
        this.jftTelefone.setEditable(valor);
    }
    
    public JLabel getjLabelID() {
        return jLabelID;
    }

    public void setjLabelID(JLabel jLabelID) {
        this.jLabelID = jLabelID;
    }

    public JTextField getJtID() {
        return jtID;
    }

    public void setJtID(JTextField jtID) {
        this.jtID = jtID;
    }

    public JLabel getjLabelMensagem() {
        return jLabelMensagem;
    }

    public JLabel getjLabelObservacao() {
        return jLabelObservacao;
    }
    
    
    
    private void jbCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCadastrarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrarCliente();            
        }
    }//GEN-LAST:event_jbCadastrarKeyPressed

    private void jtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrarCliente();            
        }
    }//GEN-LAST:event_jtNomeKeyPressed

    private void jtRGKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtRGKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrarCliente();            
        }
    }//GEN-LAST:event_jtRGKeyPressed

    private void jftTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftTelefoneActionPerformed

    private void jftTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftTelefoneKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrarCliente();            
        }
    }//GEN-LAST:event_jftTelefoneKeyPressed

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        controller.voltarPrincipal();
    }//GEN-LAST:event_jbVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelMensagem;
    private javax.swing.JLabel jLabelObservacao;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JFormattedTextField jftTelefone;
    private javax.swing.JTextField jtID;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtRG;
    // End of variables declaration//GEN-END:variables
}
